# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuildManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GuildManager
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Storage'

pod 'SideMenu'

  target 'GuildManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuildManagerUITests' do
    # Pods for testing
  end

end
